Repository 47degrees/pbdirect, pull requests merged in 2020-04, with the labels that each got.

#71 Update sbt to 1.3.9
  project/build.properties
Labels: auto-update

#72 Update actions, documentation templates and configuration files to v0.2.3
  .github/workflows/changelog.yml
  .github/workflows/docs.yml
  .github/workflows/scalasteward-auto-approve.yml
  .mergify.yml
Labels: auto-update

#73 Update actions, documentation templates and configuration files to v0.3.1
  .github/workflows/bot-prs-auto-approve.yml
  .github/workflows/changelog.yml
  .github/workflows/ci.yml
  .github/workflows/docs.yml
  .mergify.yml
Labels: auto-update

#74 Update actions, documentation templates and configuration files to v0.3.2
  .mergify.yml
Labels: auto-update

#75 Update CHANGELOG.md
  CHANGELOG.md
Labels: auto-changelog

#76 Update CHANGELOG.md
  CHANGELOG.md
Labels: auto-changelog

#77 Update actions, documentation templates and configuration files to v0.3.3
  .github/workflows/changelog.yml
  .github/workflows/docs.yml
Labels: auto-update

#78 Update actions, documentation templates and configuration files to v0.4.0
  .github/workflows/bot-prs-auto-approve.yml
  .github/workflows/ci.yml
  .github/workflows/docs.yml
Labels: auto-update

#79 Update actions, documentation templates and configuration files to v0.4.1
  .github/workflows/changelog.yml
  .github/workflows/ci.yml
  .github/workflows/docs.yml
  .github/workflows/release.yml
Labels: auto-update

#81 Update sbt to 1.3.10
  project/build.properties
Labels: auto-update

#83 Update sbt-ci-release to 1.5.3
  project/plugins.sbt
Labels: scala-steward
